### ISSUE TITLE
Add provider to pin_infos

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#10]
We need to know the source of the pins.
(Which apps pin a new pin?)
Ex. providers: [ "youpin", "greenworld", "bigtree", "hivester" ]

**Comment by parnurzeal** [comment]
Add provider: {} to the schema in firebase.k

**Comment by rapee** [comment]
As discussed earlier, `provider` is a string, not array. Only one provider for a pin is possible.

This field should be **required**.
