### ISSUE TITLE
Transition to MongoDB

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#11]
Firebase isn't intuitive enough and has inflexible functionalities enough for our requirements.
Firstly, we thought geosearch can be done within firebase but it is NOT.
Secondly, it is a paid service. Transition to MongoDB would be the best.

**Comment by parnurzeal** [comment]
Relate commit to this issues:
2c9427d2ce4aa3fb6760a844e262143e5fce40d0, 
1782ad4b21b2651b251bd27ca0e0913166dcf9ff

**Comment by supasate** [comment]
@parnurzeal Can close it now?

**Comment by parnurzeal** [comment]
Yes thx!
