### ISSUE TITLE
API Documents

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#12]
We have to create an API document for the upcoming hackathon on July 29th - 31st. 
We will use http://apidocjs.com/ and create another repo for it.

**Comment by p16i** [comment]
this service might be helpful : http://editor.swagger.io/

**Comment by parnurzeal** [comment]
Wow, good one. 
I was looking into this on at first. http://apidocjs.com/

**Comment by supasate** [comment]
@parnurzeal  Let's me help on this one. Could you create a repo for API docs (youpin-api-docs)?

I'll try with apidocjs first. I think it can also be transformed into Swagger.

**Comment by parnurzeal** [comment]
Done creating the repo! Thx!

**Comment by supasate** [comment]
Cool. Already tried one. Please check.
