### ISSUE TITLE
A user must belong to organizations with a role per organization

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-api#126]
**Requirements**
- A user can belong to multiple organizations (ex. YouPin org,  PanMuang org, etc.)
- A user has one role per org 

**Tasks**
- [x] Modify the UserSchema to contain an array of {organization, role} pairs.
- [x] Create OrganizationSchema to contains an array of users belong to each organization

**Comment by parnurzeal** [comment]
Let's change the word 'realm' to 'organization'.

**Comment by parnurzeal** [comment]
I will take this one.

**Comment by supasate** [comment]
Done by #129 #130
