### ISSUE TITLE
Add location field to pin data

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#15]
Pins should include `location` field with it.

**Comment by parnurzeal** [comment]
@rapee Now, `location` field is included in any returning pin response.

```
{
    data: [
        {id: ..., detail: ..., location: [10, 10]},
        {id: ..., detail: ..., location: [1.23, 0]}  
    ]
}
```

**Comment by parnurzeal** [comment]
@rapee @tvirot  Note that we are changing format. 
Please change the code in Web and Bot accordingly.
Thx krub!

**Comment by rapee** [comment]
Thx
