### ISSUE TITLE
Extract Firebase configuration into a config file

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-api#2]
In `app.js`,  the following firebase config is hard coded:

```
const firebaseConfig = {
  databaseURL: 'https://you-pin.firebaseio.com',
  storageBucket: 'you-pin.appspot.com',
  serviceAccount: './youpin_credentials.json',
};
```

We should extract it out into a config file in the `config` folder. So, we can test the app with other URLs without touching the `app.js` file.

**Comment by rapee** [comment]
+1
