### ISSUE TITLE
Notify all department heads when a new department is assigned to pin

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-api#255]

**Comment by parnurzeal** [comment]
I think this is also already implemented.
https://github.com/youpin-city/youpin-api/blob/master/src/services/pin-state-transition/index.js#L123

**Comment by rapee** [comment]
Nope. That was old implementation that triggers when `status` changes.

Currently, it has to trigger when `assign_department` changes. :(
@parnurzeal
