### ISSUE TITLE
Notify users when he/she is assigned to pins

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-api#256]

**Comment by parnurzeal** [comment]
This is working. The implementation is already here:
https://github.com/youpin-city/youpin-api/blob/master/src/services/pin-state-transition/index.js#L138

**Comment by rapee** [comment]
Nope. That was old implementation that triggers when `status` changes.

Currently, it has to trigger when `assigned_users` changes. :(
@parnurzeal
