### ISSUE TITLE
Allow any users to post progresses

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-api#273]
Currently, some users cannot post comments (progress) on certain pins.
I guess it has something to do with mismatch department or owner.

As of current UX, please allow anyone to post progress, no conditions.

----
PATCH `https://api.icare.eng.chula.ac.th/pins/58e21616a592357989f381a9`

```json
{
  "name":"NotAuthenticated",
  "message":"Owner field (id) does not matched with the token owner id.",
  "code":401,
  "className":
  "not-authenticated",
  "errors":{}
}
```

**Comment by supasate** [comment]
Use #277 instead
