### ISSUE TITLE
Executive-level admins does not need to get notification

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-api#276]
# Problems
Executives of the projects needs to be able to manage all issues, see all insights, the same level as organization admin. But executives do not need notifications. 

# Solutions
The first solution is to let each user configures custom notification preference. 
Or second, create a new role `executive_admin` with same level of privileges but do not get any notifications.

**Comment by parnurzeal** [comment]
Let's go for the easiest way which is to create a new `executive_admin`.

**Comment by rapee** [comment]
@parnurzeal Ok! Let's go
