### ISSUE TITLE
Add testing for Pin Model

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#46]
Please see the testing example in User model (test/services/user/index.test.js).

**Comment by parnurzeal** [comment]
PR #54 also helps solving this issue.

**Comment by supasate** [comment]
Should we let this issue open?

**Comment by parnurzeal** [comment]
Yes, this is not done yet. I only added POST and GET tests.

**Comment by parnurzeal** [comment]
Obsolete
