### ISSUE TITLE
Create routing for video upload

### ISSUE THREAD

**Issue by parnurzeal** [youpin-city/youpin-api#56]
This should be similar to photo upload routing.

**Comment by supasate** [comment]
Let me do it.

**Comment by parnurzeal** [comment]
Reviewed. PTAL.

**Comment by parnurzeal** [comment]
@tvirot  @rapee  Can you help testing it?
it is merged and deployed to https://dev.api.youpin.city

**Comment by supasate** [comment]
Done.
