### ISSUE TITLE
Remove duplicate tags before saving a pin

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-api#62]
Related to youpin-city/youpin-bot#9.

**Comment by p16i** [comment]
I can take a look at this issue.

**Comment by supasate** [comment]
@heytitle Thx. Yesterday, we just discussed about this issue. 

In this case, a user writes body text thats contains a hash tag which is the same as the category tag. 

The API is alright to send the body text and tags out, but, a tag which is already in the body text should be removed in the display logic.

So, you can help contribute in [youpin-ciy/youpin-web](https://github.com/youpin-city/youpin-web) instead. I just open youpin-city/youpin-web#9 for this issue.

If you need any help, please let us know. (@rapee is the main contributor in that repo. Feel free to ask him also.)
