### ISSUE TITLE
Build resource ID internally

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-api#7]
It's be nicer if I can use ID of the resource without having to extract it from object key.

Instead of:

```
pin_info: {
  'abc': { neighborhood: 'silom' },
  'abd': { neighborhood: 'samyan' },
}
```

Should be:

```
pin_info: [
  { id: 'abc', neighborhood: 'silom' },
  { id: 'abd', neighborhood: 'samyan' },
]
```

What do you think? @parnurzeal

**Comment by parnurzeal** [comment]
It is now builtin internally. 
When you do POST, it will add generated key as an "id" in the object.

And when you GET, it will return as an array but also note that the format is changed a bit to:

```
{
data: [
  { id: 'abc', neighborhood: 'silom' },
  { id: 'abd', neighborhood: 'samyan' },
]
}
```

**Comment by parnurzeal** [comment]
Additionally, `location` field is also built in each object.

```
{
data: [
  { id: 'abc', neighborhood: 'silom' , location: [10, 10]},
  { id: 'abd', neighborhood: 'samyan', location: [0, 0]},
]
}
```
